### ISSUE TITLE
Update to latest versions of conventional-changelog

### ISSUE THREAD

**Issue by kentcdodds** [semantic-release/release-notes-generator-v3#4] opened 2017-04-06 04:32 UTC
I found that my release notes have invalid HTML:

```html
<a name"1.0.1">
```

Note the missing `=`. This means that not only does the anchor tag not work as it should, it also is rendered as text in my changelog:

<img width="205" alt="screen shot 2017-04-05 at 10 27 43 pm" src="https://cloud.githubusercontent.com/assets/1500684/24737865/1d099dbc-1a4f-11e7-8f4e-c5852da65538.png">

In investigating what was causing this, I found [this file](https://github.com/conventional-changelog-archived-repos/conventional-changelog-writer/blob/8b21226e4c1b4861d3737e6bd57125fb03be3c7f/templates/header.hbs#L1) which I assumed was the template, but I was surprised to see that the template looks correct (includes the `=`). I assumed this is because the bug was fixed and we're using an older version here and my assumption was correct! However, it looks like we're using an _extremely_ old version and the `conventional-changelog` project as a whole has moved on.

I'm not sure of the effort it would take to upgrade this (and probably `@semantically-released/commit-analyzer` as well), but I would very much like it to be. Perhaps I can find time to do that myself, or someone else can. But I thought I'd drop this in here to show the amount of research I've done so far.

What's left:

- [x] determine the significant breaking changes to get us onto the latest version
- [x] submit a PR to upgrade things
- [x] get the PR reviewed/merged
- [ ] release the new version (ironically, this is not automated)

I'll chime in again if I start working on it. Anyone else can feel free to do so.

**Comment by uglow** [comment] 2017-04-11 04:31
I've been noticing this for several months too. I thought it was fixed, but it was only fixed within corp-semantic-release (a module which emulates semantic-release for corporate environments).

**Comment by felixfbecker** [comment] 2017-06-21 13:14
Could a maintainer comment on this? We recently switched [Sequelize](https://github.com/sequelize/sequelize) (NodeJS ORM, 10k stars, 400k downloads/month) to semantic-release and seeing a bug like this caused by super-outdated dependencies is worrying to say the least... Greenkeeper could ease this, but [the PR](https://github.com/semantic-release/release-notes-generator/pull/3) is open for a long time now. @boennemann?

**Comment by gr2m** [comment] 2017-08-12 00:36
hey folks I’m looking into this now, Stephan invited me as maintainer. Expect more activity over the next months again :)

**Comment by kentcdodds** [comment] 2017-08-12 01:38
Gregor, I am so happy to hear you say that 🤗

**Comment by kentcdodds** [comment] 2017-08-12 01:38
Except... I guess I'm not really hearing you... But you know what I mean I think.

**Comment by gr2m** [comment] 2017-08-12 18:42
I’ll keep you all posted in this issue moving forward: https://github.com/semantic-release/semantic-release/issues/411 Thanks for your patience and if you could help triaging open issues / PRs and mention me in the ones you think are most urgent, I’d appreciate it <3

**Closed as completed** 2017-08-12 19:32 UTC

**Comment by gr2m** [comment] 2017-08-13 19:29
I’ve released `semantic-release@7.0.0` with the next release. You can install it with `npm install --save-dev semantic-release@next` or directly set the version in your projects’ `package.json` files.

This should resolve the issue. Please give it a try and let me know if it works as expected, once a few folks tested it we can set the `semantic-release@7.0.0` to `@latest`

**Comment by kentcdodds** [comment] 2017-08-14 19:09
I used `semantic-release@7.0.1` in [this build](https://travis-ci.org/kentcdodds/babel-plugin-codegen/builds/264478289) and [it worked!](https://github.com/kentcdodds/babel-plugin-codegen/releases/tag/v1.1.1). The bug is gone :tada:
